GET http://localhost:5109/groups/
Accept: application/json

###

GET http://localhost:5109/groups/2

###

POST http://localhost:5109/groups/
Content-Type: application/json

{
    "name": "Group 1"
}

###

GET http://localhost:5109/members/

###

POST http://localhost:5109/members/
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Johnson",
    "groupId": 1,
    "money": 19.20
}